# Generated by Django 3.1.4 on 2020-12-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='image',
            field=models.URLField(),
        ),
    ]
